
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  myredis:
    host: 115.159.213.143
    port: 6379
    database: 15
  activemq:
    broker-url: tcp://115.159.213.143:61616
    listener:
      enable: true
dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://115.159.213.143:2182
  protocol:
    port: -1
  consumer:
    check: false
  scan:
    base-packages: com.qc.mall
server:
  port: 7000
