server:
  port: 8003
dubbo:
  application:
    name: search-web
  registry:
    address: zookeeper://115.159.213.143:2182
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 3000
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#logging:
#  level:
#    root: debug

